### PR TITLE
Fix css generation

### PR DESCRIPTION
**Pull request by razbakov**
- fix sticky
- add missing icons
- update readme

Related [ch605]

### CODE REVIEW

**Comment by eFzvai** [comment]
Ticket is missing

**Comment by razbakov** [comment]
Yeap, like [here](https://github.com/banovo/backoffice-api/commit/33e5a89b169b8942c9fe5d589e986727b56e64b0)

**Comment by eFzvai** [comment]
We have talk about that and we want no pull request without a ticket

**Comment by razbakov** [comment]
@eFzvai updated PR comment. I will squash PR and it will be in commit message also.

**Pull request merged**
